# yamllint disable rule:line-length
---
  name: Dummy Workflow
  permissions:
    contents: read
  on:
    workflow_dispatch:
  
  jobs:
    prepare:
      runs-on: ubuntu-20.04
      name: Generate data for jobs
      outputs:
        linux: ${{steps.data.outputs.linux}}
      steps:
        - name: Generate data
          id: data
          shell: bash
          run: |
            linux="{"
            for type in "client" "desktop" "plugins";
            do
              linux+="\"${type}_coverage\":75.0,\"${type}_count\":1234,"
            done
            linux=${linux%?}
            linux+="}"
            echo "linux=${linux}" >> "$GITHUB_OUTPUT"

    process:
      needs: prepare
      runs-on: ubuntu-20.04
      name: Process data for jobs
      env:
        INPUT: ${{needs.prepare.outputs.linux}}
      steps:
        - name: Process data
          shell: bash
          run: |
            for type in "client" "desktop" "plugins";
            do
              coverage=$(echo $INPUT | jq -r .${type}_coverage)
              count=$(echo $INPUT | jq .${type}_count)
              echo "${type}: ${coverage}%, ${count} tests"
            done